Changed build script to handle errors

diff --git a/visualizer/botnet/windowsBotnet b/visualizer/botnet/windowsBotnet
--- a/visualizer/botnet/windowsBotnet
+++ b/visualizer/botnet/windowsBotnet
@@ -8,9 +8,21 @@ cp -R output/visualizer/* ../visualizer/botnet/parser
 pwd
 
 cd ../visualizer/botnet/parser/sexp
+if [ "$?" -ne "0" ]; then
+  echo "Could Not Build the Parser"
+  exit 1
+fi
 make
+if [ "$?" -ne "0" ]; then
+  echo "Could Not Build the Parser"
+  exit 1
+fi
 cd ../
 make
+if [ "$?" -ne "0" ]; then
+  echo "Could Not Build the Parser"
+  exit 1
+fi
 cd ../
 
 make clean
