Make the windowsBuild script correct

diff --git a/visualizer/windowsBuild b/visualizer/windowsBuild
--- a/visualizer/windowsBuild
+++ b/visualizer/windowsBuild
@@ -1,36 +1,18 @@
 #!/bin/bash
 
-# Run the codegen and get the files
-
-# Get to the codegen
-cd ../codegen/
-
-# Run it
-python main.py templates
-
-# Copy the appropriate files over
-cp -f -r ./output/visualizer/* ../visualizer/lib/parser/
-
-# First compile parser for linux
-# Get to Parser directory:
-cd ../visualizer/lib/parser
-
-# We want to remove all linux binaries and helper files
-make clean
-
-# Build Parser for Windows:
-make TARGET=mingw
-
-# Congrats, a windows parser has now been built for you.
-
-# Back to the root directory:
-cd ../../
-
 # Build Makefiles for windows:
 qmake -spec win32-x-g++
+if [ "$?" -ne "0" ]; then
+  echo "Could not build the windows makefiles.  Check output."
+  exit 1
+fi
 
 # Leave off release if you want a debug build
 make release
+if [ "$?" -ne "0" ]; then
+  echo "Could not build the windows binaries.  Check output."
+  exit 1
+fi
 
 # Clean up windows mess
 make clean
